parameters:
    who.charted.config_provider.class:  Jov\Bundle\WhoChartedBundle\Model\ConfigProvider
    who.charted.class:                  Jov\Bundle\WhoChartedBundle\Model\WhoChartedBuilder

services:
    who.charted.config_provider:
        class: %who.charted.config_provider.class%
        arguments:
            - []
    who.charted:
        class: %who.charted.class%
        arguments:
            - @who.charted.config_provider
            - @oro_chart.data_transformer.factory
            - @twig
