jov_who_charted:
    bar_chart:
        label: jov.who_charted.bar_chart.label
        default_settings:
            colors:
                - fillColor: 'rgba(4,77,41,.6)'
                  strokeColor: 'rgba(0,38,28,.6)'
                  highlightFill: 'rgba(69,191,85,.6)'
                  highlightStroke: 'rgba(22,128,57,.6)'
        template: JovWhoChartedBundle:Chart:bar.html.twig

    line_chart:
        label: jov.who_charted.line_chart.label
        default_settings:
            colors:
                - fillColor: "rgba(4,77,41,.6)"
                  strokeColor: "rgba(0,38,28,.6)"
                  pointColor: "rgba(22,128,57,.6)"
                  pointStrokeColor: "rgba(0,38,28,.6)"
                  pointHighlightFill: "rgba(69,191,85,.6)"
                  pointHighlightStroke: "rgba(220,220,220,1)"
        template: JovWhoChartedBundle:Chart:line.html.twig

    radar_chart:
        label: jov.who_charted.radar_chart.label
        default_settings:
            colors:
                - fillColor: "rgba(4,77,41,.6)"
                  strokeColor: "rgba(0,38,28,.6)"
                  pointColor: "rgba(22,128,57,.6)"
                  pointStrokeColor: "rgba(0,38,28,.6)"
                  pointHighlightFill: "rgba(69,191,85,.6)"
                  pointHighlightStroke: "rgba(220,220,220,1)"
        template: JovWhoChartedBundle:Chart:radar.html.twig

    polar_chart:
        label: jov.who_charted.polar_chart.label
        default_settings:
            colors:
                - color: "red"
                  highlight: "blue"
                - color: "purple"
                  highlight: "lightblue"
        template: JovWhoChartedBundle:Chart:polar.html.twig

    pie_chart:
        label: jov.who_charted.polar_chart.label
        default_settings:
            colors:
                - color: "red"
                  highlight: "blue"
                - color: "purple"
                  highlight: "lightblue"
        template: JovWhoChartedBundle:Chart:pie.html.twig

    doughnut_chart:
        label: jov.who_charted.doughnut_chart.label
        default_settings:
            colors:
                - color: "red"
                  highlight: "blue"
                - color: "purple"
                  highlight: "lightblue"
        template: JovWhoChartedBundle:Chart:doughnut.html.twig
